bluez: Autospec creation for update from version 5.68 to version 5.69
Bart Philips (1):
      shared/gatt-server: Fix not allowing valid attribute writes

Claudia Draghicescu (10):
      monitor: Add decoding support for Sync Receiver events
      client/player: Add broadcast sink endpoint
      btio: Add support for getsockopt(BT_ISO_BASE)
      adapter: Do not filter out broadcast advertiser
      shared/bap: Add support for BAP broadcast sink
      bap: Add support for BAP broadcast sink
      media: Add broadcast sink media endpoint
      transport: Update transport properties for a broadcast stream
      client/player: Remove Broadcast parameter
      adapter: Fix UUID name advertised for bcast source

Gioele Barabucci (2):
      configure.ac: Bump minimum D-Bus version to 1.10
      configure.ac: Install D-Bus policy in /usr/share, not /etc

Grzegorz Kolodziejczyk (1):
      monitor: Fix invalid Create BIG Test command

Iulia Tanasescu (4):
      btio: Add options for binding iso broadcast address
      shared/bass: Introduce Add Source opcode handler
      iso-tester: Add test for bcast receiver defer setup
      isotest: Add defer setup support for Broadcast Receiver

Jakub Tyszkowski (1):
      monitor: Fix adv_handle size in the set info transfer packet

Karl Bieber (1):
      main: Fix missing comma

Lokendra Singh (1):
      monitor/intel: Add decoding of PPAG Enable command

Luiz Augusto von Dentz (48):
      test-runner: Add documentation
      mgmt-tester: Fix tests that consider 31 bytes the max adv lenght
      shared/ad: Fix hardcoding maximum data length
      advertising: Use bt_ad_set_max_len
      client/advetising: Allow use of EA data length
      advertising: Fix build warning
      shared/ad: Use util_iov_push_* helpers to generate data
      main: Remove DEFAULT_SIRK
      shared/util: Introduce strisutf8
      shared/ad: Make use of util_iov_pull_* to parse data
      test-eir: Run tests using bt_ad
      bthost: Add support to set ISO Packet Status
      iso-tester: Add test for BT_PKT_STATUS sockopt
      client: Add support for mgmt submenu
      midi: Fix build errors
      btmgmt: Add man page
      client: Add bluetoothctl-mgmt.1 man page
      client: Add bluetoothctl-monitor.1 man page
      bap: Fix memory leaks
      monitor: Use gnuplot to plot graph of Latency-Packets
      monitor: Update documentation
      monitor: Consolidate code around latency calculation
      monitor: Fix not dequeing TX packet properly
      monitor: Fix not calculating latency for ISO/SCO packets
      monitor/analyze: Fix not dequeing TX packet properly
      monitor/analyze: Fix not calculating latency for ISO/SCO packets
      gatt: Fix not establishing a socket for each device
      monitor: Add TX frame number and speed estimation
      monitor/analyze: Use conn_pkt_tx on acl_pkt
      monitor: Print channel latency information with -a/--analyze
      monitor: Add connection tracking for SCO/ISO with -a/--analyze
      monitor/analyze: Inline data to gnuplot
      iso-tester: Fix test ISO Connect2 CIG 0x01 - Success/Invalid
      monitor: Plot RX information with -a/--analyze
      eir: Add eir_get_service_data
      profile: Add probe_on_discover flag
      device: Fix not probing drivers at startup
      doc/test-runner: Update documentation using rst format
      iso-tester: Add suspend tests
      build: Fix make distcheck
      monitor: Fix not printing latency information with -r
      monitor: Detect LE-ACL connections
      bap: Set auto_connect
      profile: Remove probe_on_discover
      device: Don't attempt to set auto_connect for devices using RPAs
      device: Restart temporary timer while connecting
      client: Add agent auto argument support
      transport: Fix crash with broadcast properties

Marcel Holtmann (3):
      build: Update library version
      build: Add generated manual pages to .gitignore
      Release 5.69

Nitin Jadhav (3):
      shared/vcp: Fix the crash observed with VOCS
      shared/vcp: Fix issues of audio location and descriptor
      shared/vcp: Reserve one more handle in VCS for VOCS

Pauli Virtanen (20):
      transport: handle BAP Enabling state correctly when resuming
      shared/bap: use only nonzero req->id
      doc/tester-config: enable DEBUG_KERNEL, PROVE_RCU, DEBUG_ATOMIC_SLEEP
      mgmt-tester: Add a regression test hitting hci_sync bug
      shared/bap: detach io for source ASEs only after Stop Ready
      bap: wait for CIG to become configurable before recreating CIS
      test-runner: set non-quiet printk before running tests
      test-runner: fix behavior when no audio server
      btdev: check error conditions for HCI_Create_Connection_Cancel
      btdev: fix Command Status command opcodes for Setup Sync Conn
      sco-tester: test local and remote disconnecting simultaneously
      iso-tester: test with large CIS_ID and invalid CIG_ID/CIS_ID
      iso-tester: add tests checking Remove CIG is emitted
      btdev: fix CIG ID on Set CIG Parameters error response
      iso-tester: test busy CIG error does not drop existing connections
      vhci: Add function to pause processing input from vhci
      hciemu: Add hciemu_flush_client_events for ordering VHCI vs bthost
      sco-tester: add test for ACL disconnect before SCO established
      iso-tester: add test for ACL disconnect before ISO created
      adapter: wait for kernel exp features in adapter initialization

Rudi Heitbaum (1):
      configure: Fix check ell path for cross compiling

Silviu Florian Barbulescu (1):
      Rename BAA_SERVICE to BCAA_SERVICE add BAA_SERVICE(0x1851)

Simon Mikuda (7):
      adapter: Fix generating IRK for adapter with privacy enabled
      advertising: Fix peripheral adverts when Discoverable = false
      gatt-client: Add read-only handles to dbus
      adapter: Be able to use ConnectDevice for discovered devices
      adapter: Update ConnectDevice documentation
      error: Add "Invalid exchange" mapping
      a2dp: Expose "Key missing" error

Szymon Czapracki (1):
      monitor/ll: Add support for connection parameter command.

Vlad Pruteanu (1):
      plugins/admin: Fix heap-use-after-free when using 2 controllers

Zijun Hu (1):
      main: Fix integer configuration option parse failures

Łukasz Rymanowski (6):
      btmon: Fix obvious typo
      btmon: Make BIG identifier consistent
      monitor: Fix decoding Command Complete for Remove ISO Data path
      monitor: Update le event mask with bits 20-23
      monitor: Add support to decode le read ISO link quality
      monitor: Add parsing Service Data of UUID 128