bluez: Autospec creation for update from version 5.60 to version 5.62
Alain Michaud (1):
      shared/shell: don't allow completion fallback

Archie Pusaka (14):
      lib: Inclusive language changes
      btio: Inclusive language changes
      monitor: Inclusive language changes
      emulator: Inclusive language changes
      tools: Inclusive language changes
      tools: Deprecate some input parameters to align with inclusive language
      plugins/sixaxis: Inclusive language changes
      profiles: Inclusive language changes
      src: Inclusive language changes
      client: Inclusive language changes
      mesh: Inclusive language changes
      unit/mesh: Inclusive language changes
      doc: Inclusive language update
      device: Check both bearers's paired status upon removal of connection

Bernie Conrad (1):
      gatt: Fix not cleaning up when disconnected

Brian Gix (3):
      tool/mgmt-tester: Add test cases for Read Clock Information API
      tool/mgmt-tester: Add fail_tolerant exception
      tools/mgmt-tester: Add Read OOB Ext Data test cases

Dagan Martinez (3):
      gatt: remove superfluous extended properties
      doc/gatt-api: Add 'X-notify`/`X-indicate`
      gatt: Allow GATT server to dicate CCC permissions

David Lechner (2):
      device: clear eir_uuids list on disconnect
      device: set le_state.svc_resolved = false in gatt_cache_cleanup()

Dylan Van Assche (2):
      obexd: phonebook-ebook: modernize
      configure.ac: add libebook dependency

Fabrice Fontaine (1):
      media: Fix build with glibc >= 2.34

Hannu Mallat (1):
      obexd: phonebook: Set default apparams for PTS clients

Inga Stotland (21):
      tools/mesh-cfgclient: Save provisioner info
      tools/mesh-cfgclient: Add timestamp to config database
      tools/mesh-cfgclient: Update stored NetKey and AppKey
      tools/mesh-cfgclient: Keep track of updated keys
      tools/mesh: Add new info to stored remote nodes
      tools/mesh-cfgclient: Overwrite config values when adding new ones
      tools/mesh-cfgclient: Store remote node's model bindings
      tools/mesh-cfgclient: Store remote node's model subs
      tools/mesh-cfgclient: Disallow model commands w/o composition
      tools/mesh-cfgclient: Store remote's model publication info
      tools/mesh-cfgclient: Check the result of config save
      tools/mesh-cfgclient: Rename mesh-db APIs for consistency
      tools/mesh-cfgclient: Save remote node feature setting
      tools/mesh-cfgclient: Store remote's heartbeat sub/pub
      tools/mesh-cfgclient: Add group parent address for DB compliance
      doc/mesh-api: Add ExportKeys call
      mesh: Implement ExportKeys() method
      tools/mesh-cfgclient: Store UUIDs in standard format
      tools/mesh-cfgclient: Excluded addresses property
      tools/mesh-cfgclient: Export configuration database
      tools/mesh-cfg-client: Fix NULL pointer dereferencing

Joseph Hwang (4):
      monitor: add new Intel extended telemetry events
      adapter: read quality report feature
      tools: btmgmt: support quality experiment feature command
      tools/mgmt-tester: add a exp feature to Read Exp Feature - Success

Juho Hamalainen (1):
      configure.ac: specify phonebook plugin at build time

Kiran K (6):
      emulator: Add support enhanced SCO connection
      mgmt: Set offload codec mgmt feature
      shared/util: Decode BlueZ offload codec UUID
      tools/sco-tester: add test cases to get offload codecs
      tools/sco-tester: Add a test case for setting offload codec
      tools/sco-tester: add a test case for offload SCO connect

Luiz Augusto von Dentz (59):
      btdev: Add proper checks for own_addr_type for extended advertising
      btdev: Add proper checks for own_addr_type for LE scan/adv
      btdev: Fix not checking conditions for LE Set Random Address
      adapter: Fix storing discoverable setting
      gatt: Add support for Central Address Resolution characteristic
      main.conf: Revert default for Privacy and Experimental
      a2dp: Invalidate cache if SetConfiguration fails
      btdev: Add proper handling for own_address_type 0x03
      monitor: Fix median packet size
      monitor: Fix minimun packet latency
      monitor: Fix not accouting for multiple outstanding packets
      monitor: Make --analyze output latencies in msec
      monitor: Make --analyze print address OUI
      advertising: Fix failing to advertise with Includes=local-name
      client/advertising: Fix not disabling local-name in Includes
      bthost: Add bthost_debug and use it on smp.c
      bthost: Fix not initializing address types properly
      adapter: Simplify setting of experimental debug feature
      adapter: Fix warning when exit
      main: Add missing Experimental entry to General options
      btdev: Fix sending terminate advertising event to the wrong device
      btdev: Fix order of BT_HCI_EVT_LE_ADV_SET_TERM
      btdev: Fix removing advertising set if it was terminated
      device: Remove GATT Attribute when device is removed
      shared/att: Fix accepting Exchange MTU on EATT bearer
      shared/att: Fix attempting to send Exchange MTU on EATT bearer
      gatt: Do not always attempt to connect EATT immediately
      test-runner: Enable bluetoothd debug when running with -d
      monitor: Fix calculation of RFCOMM length
      adapter-api: Add ExperimentalFeatures property
      adapter: Implement ExperimentalFeatures property
      client: Add support for printing ExperimentalFeatures property
      main.conf: Allow passing a list of UUIDs to Experimental
      adapter: Enable codec offload when Experimental is set
      shared/util: Add conversion function for 24 bits
      shared/util: Update UUID database with LE Audio services
      sco-tester: Add tests for sending data
      service: Add btd_service_is_initiator
      policy: Use btd_service_is_initiator
      admin: Fix leaking uuids loads from storage
      admin: Fix double free
      media: Add media_player prefix for callback
      shared/mgmt: Set MTU to UINT16_MAX
      lib: Fix HCI_MAX_ACL_SIZE
      shared/mgmt: Add mgmt_get_mtu
      adapter: Truncate number of LTKs loaded if over MGMT MTU
      avctp: Fix not handling when kernel has ERTM disabled
      avrcp: Fix browsing support in SDP record
      doc/tester-config: Enable Android Extension
      doc/tester-config: Enable KASAN
      gatt-api: Add MTU property to GattCharacteristic1
      gatt: Add implementation of GattCharacteristic1.MTU
      shared/att: Add bt_att_register_exchange
      gatt: Emit PropertiesChanged("MTU") when MTU is exchanged
      client: Print MTU on attribute-info
      shared/att: Add bt_att_resend
      shared/gatt-client: Make use of bt_att_resend
      attrib: Make use of bt_att_resend
      test-hog: Update pdu sequence

Manish Mandlik (2):
      adv_monitor: Clear any running DeviceLost timers on power down
      adv_monitor: Mark the device as lost on device_lost_timeout

Marcel Holtmann (12):
      monitor: Remove unneeded fprintf for unknown opcodes
      monitor: Add ISO packets to analyze option
      monitor: Count number of control messages
      monitor: Remove unneeded fprintf for new devices
      monitor: Track connections for analyze function
      monitor: Add further stats to analzye functionality
      monitor: Store MSFT extension event prefix
      monitor: Track L2CAP packets for analyze function
      monitor: Track PSM for L2CAP analyze function
      Release 5.61
      build: Update library version
      Release 5.62

Marijn Suijten (2):
      audio/avrcp: Use host/network order as appropriate for pdu->params_len
      audio/transport: Only store volume when also emitting DBus prop change

Mariusz Skamra (3):
      monitor: Fix truncated server socket path parameter
      monitor: Fix Maximum PDU type in CIS Test Param
      monitor: Fix logging of CIG Test SDU Interval param

Miao-chen Chou (4):
      doc: Add errors.txt to describe errors of D-Bus method returns
      error: BR/EDR and LE connection failure reasons
      device: Include detailed error string in Connect() return
      client: Print error code for connect methods

Pauli Virtanen (2):
      shared/util: use 64-bit bitmap in util_get/clear_uid
      avdtp: use separate local SEID pool for each adapter

Peter A. Bigot (1):
      lib: Fix variable-length array declarations in hci structures

Sonny Sasaka (1):
      monitor: Print EIR of Extended Advertisement Report

Tedd Ho-Jeong An (14):
      emulator/btdev: Add support HCI_READ_CLOCK command
      monitor: Add support for tlv based version format for Intel vendor
      doc: Add a doc for Intel hardware variants
      tools/mgmt-tester: Update exp feature testcase
      tools: userchan-tester: Add test case for the closing channel
      doc/tester-config: Enable Microsoft Extension
      tools/mgmt-tester: Fix Read Experiemental Feature test case
      tools/mgmt-tester: Add suspend/resume test cases
      tools/mgmt-tester: Add test cases for load_long_term_keys command
      tools/mgmt-tester: Fix the suspend reason code
      tools/mgmt-tester: Update the correct suspend reason for disconnect
      doc/tester-config: Enable Runtime Debugging Feature
      tools/mgmt-tester: Updates Experimental Feature test cases
      tools/mgmt-tester: Add more suspend/resume test cases

Thomas Weißschuh (1):
      Use accurate icons for headphones and headsets

Yun-Hao Chung (25):
      src/adv_monitor: Remove checking in device lost timeout
      a2dp: Fix crash in channel_free while waiting cmd resp
      core: fix a possible crash when removing devices
      gatt-db: remove redundant check in foreach range
      core: add is_allowed property in btd_service
      core: add device callbacks to adapter driver
      core: add adapter and device allowed_uuid functions
      core: block not allowed UUID connect in auth
      plugins: new plugin
      plugins/admin: add admin_policy adapter driver
      plugins/admin: add ServiceAllowList method
      plugins/admin: add ServiceAllowList property
      plugins/admin: add device callbacks
      plugins/admin: add AffectedByPolicy property
      plugins/admin: persist policy settings
      doc: add description of admin policy
      doc: add admin policy file storage description
      shared/shell: fix missing stdbool in shell.h
      client: add admin submenu and allow command
      client: add AffectedByPolicy property
      plugins/admin: add uuid duplicate check
      btmgmt: add non-interactive quit on read-sysconfig
      plugin/admin: fix set empty allowlist no persistence issue
      plugins/admin: add adapter_remove handler
      plugins/admin: create admin_policy_settings if not exists